# Logistic Regression Math

## Import libraries

In [1]:
import numpy as np

## Make up some data

We need some data points. We are going to fake it by creating 100 x 2 normally distributed matrix

In [2]:
N = 100
D = 2

X = np.random.randn(N, D)

We are going to use 0 = W * X + b line as a separator, or

b + w1 * x1 + w2 * x2 + ... wn * xn = 0

bias b is kind of ruining the uniformity. We could think of it as of w0 and we could also think that it is multiplied by x0 that is always 1.
So we get:

w0 * x0 + w1 * x1 + w2 * x2 + ... wn * xn = 0

or, back to vector form,

0 = W * X

That is super nice, so we are going to simply add a column of ones to our data point matrix:

In [3]:
ones = np.ones((N, 1))
Xb = np.concatenate((ones, X), axis=1)

In [4]:
Xb[:5]

array([[ 1.        , -2.56430484,  1.42974385],
       [ 1.        , -0.68284638, -1.15976123],
       [ 1.        ,  0.55256505,  0.15595912],
       [ 1.        , -0.11376352,  2.42438069],
       [ 1.        , -0.46114705, -0.94200178]])

## Generate Weights

In [5]:
w = np.random.randn(D + 1)

In [6]:
w

array([ 0.41892576, -0.64654742,  0.23495881])

## Calculate Prediction

In [7]:
z = Xb.dot(w)

In [8]:
z[:5]

array([2.41280135, 0.58792221, 0.09831023, 1.06210889, 0.49574758])

## Apply Sigmoid

In [9]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

In [10]:
z1 = sigmoid(z)

In [11]:
z1[:20]

array([0.91779828, 0.64288826, 0.52455778, 0.74309335, 0.62145948,
       0.47821868, 0.69878439, 0.8304764 , 0.83234358, 0.49093173,
       0.52497692, 0.51160587, 0.73219601, 0.66311651, 0.59546539,
       0.75502164, 0.50645391, 0.30898434, 0.61606875, 0.6576126 ])